name: Validate Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Validate Branch Name
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$BRANCH_NAME" =~ ^(feature|hotfix|setup|spike|documents)/[0-9]+/[a-zA-Z0-9_-]+$ ]]; then
            echo "Branch name $BRANCH_NAME does not follow the naming convention (e.g., feature/13/integration-domain)."
            exit 1
          fi
